/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "State_CtrlReg_Run.h"
#include "State_CtrlReg_Dir.h"
#include "State_State.h"
#include "State_defs.h"
#include "C.h"
#include "C_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "A.h"
#include "A_aliases.h"
#include "D.h"
#include "D_aliases.h"
#include "Clock_2.h"
#include "P0_0_clk.h"
#include "P0_0_clk_aliases.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

