# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Anders\Documents\Projekt 4. semester\HellYaeh\Retning\Beast.cydsn\Beast.cyprj
# Date: Wed, 02 Nov 2016 14:26:39 GMT
#set_units -time ns
create_clock -name {I2CS_SCBCLK(FFB)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock_PWM} -source [get_pins {ClockBlock/hfclk}] -edges {1 481 961} [list [get_pins {ClockBlock/udb_div_0}]]
create_generated_clock -name {I2CS_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 2 3} [list]


# Component constraints for C:\Users\Anders\Documents\Projekt 4. semester\HellYaeh\Retning\Beast.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Anders\Documents\Projekt 4. semester\HellYaeh\Retning\Beast.cydsn\Beast.cyprj
# Date: Wed, 02 Nov 2016 14:26:37 GMT
