/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "State_front_engine_CtrlReg_Run.h"
#include "State_front_engine_CtrlReg_Dir.h"
#include "State_front_engine_State.h"
#include "State_front_engine_defs.h"
#include "Clock_1.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2CS.h"
#include "I2CS_PVT.h"
#include "A_front_aliases.h"
#include "A_front.h"
#include "B_front_aliases.h"
#include "B_front.h"
#include "C_front_aliases.h"
#include "C_front.h"
#include "D_front_aliases.h"
#include "D_front.h"
<<<<<<< HEAD
#include "State_back_engine_CtrlReg_Run.h"
#include "State_back_engine_CtrlReg_Dir.h"
#include "State_back_engine_State.h"
#include "State_back_engine_defs.h"
#include "PWM_foreste_fremdrift.h"
#include "PWM_Fremdrift_bag_aliases.h"
#include "PWM_Fremdrift_bag.h"
#include "PWM_Fremdrift_for_aliases.h"
#include "PWM_Fremdrift_for.h"
#include "PWM_bagerste_fremdrift.h"
=======
#include "VDAC8_B.h"
#include "PWM_front_engine.h"
#include "Pwm_back_aliases.h"
#include "Pwm_back.h"
#include "Pwm_front_aliases.h"
#include "Pwm_front.h"
#include "PWM_back_engine.h"
>>>>>>> 40a74277513dcec9fbc43d3e105e642a69e6a52f
#include "D_back_aliases.h"
#include "D_back.h"
#include "C_back_aliases.h"
#include "C_back.h"
#include "B_back_aliases.h"
#include "B_back.h"
#include "A_back_aliases.h"
#include "A_back.h"
<<<<<<< HEAD
#include "test_aliases.h"
#include "test.h"
#include "PWM_for_retning_voltreguator.h"
#include "PWM_Voltreg_for_aliases.h"
#include "PWM_Voltreg_for.h"
#include "Clock_2.h"
#include "PWM_bag_retning_voltreguator.h"
#include "PWM_Voltreg_bag_aliases.h"
#include "PWM_Voltreg_bag.h"
=======
#include "Clock_2.h"
#include "VDAC8_A.h"
#include "PGA_A.h"
#include "Comp_A.h"
#include "Sense_A_aliases.h"
#include "Sense_A.h"
#include "PGA_B.h"
#include "Comp_B.h"
#include "Sense_B_aliases.h"
#include "Sense_B.h"
>>>>>>> 40a74277513dcec9fbc43d3e105e642a69e6a52f
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

