/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "stepF_aliases.h"
#include "stepF.h"
#include "Clock_2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "I2CS.h"
#include "I2CS_PVT.h"
#include "Dir_stepF_aliases.h"
#include "Dir_stepF.h"
#include "PWMF1.h"
#include "PWMF2.h"
#include "CounterF.h"
#include "PWMSF.h"
#include "Clock_3.h"
#include "SpeedForW_aliases.h"
#include "SpeedForW.h"
#include "Clock_4.h"
#include "stepB_aliases.h"
#include "stepB.h"
#include "Clock_5.h"
#include "Dir_stepB_aliases.h"
#include "Dir_stepB.h"
#include "CounterB.h"
#include "PWMB2.h"
#include "PWMB1.h"
#include "PWMSB.h"
#include "Clock_6.h"
#include "SpeedBackW_aliases.h"
#include "SpeedBackW.h"
#include "MicroF_aliases.h"
#include "MicroF.h"
#include "MicroB_aliases.h"
#include "MicroB.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

