/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM1.h"
#include "Clock_1.h"
#include "Counter.h"
#include "step_aliases.h"
#include "step.h"
#include "Clock_2.h"
#include "I2CS.h"
#include "I2CS_PVT.h"
#include "sda_aliases.h"
#include "sda.h"
#include "scl_aliases.h"
#include "scl.h"
#include "Dir_step_aliases.h"
#include "Dir_step.h"
#include "PWM2.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

